LANG    = CSharp
TEST    = chameneos-redux
SOURCE  = Program.cs
OUTPUT  = bin/Release/chameneos-redux
ARG     = 6000000
RUN_CMD = dotnet run --configuration Release -- $(ARG)

COMPILE_CMD = dotnet build --configuration Release --nologo

include ../../../perfarena.mk
