LANG        = Ruby
TEST        = binary-trees
SOURCE      = binarytrees.yarv-5.yarv
OUTPUT      = binary-trees.rb
ARG         = 21
RUN_CMD     = ruby $(OUTPUT) $(ARG)
COMPILE_CMD = cp $(SOURCE) $(OUTPUT)

VALIDATION_N       = 10
REFERENCE_OUTPUT   = ../../../reference/clbg/outputs/binary-trees.txt

include ../../../perfarena.mk
