LANG    = C++
TEST    = mandelbrot
SOURCE  = mandelbrot.gpp-6.c++
OUTPUT  = mandelbrot.gpp_run
ARG     = 14
RUN_CMD = ./$(OUTPUT) $(ARG)

CXXFLAGS ?= -O3 -fomit-frame-pointer -std=c++14 -fopenmp

COMPILE_CMD = $(CXX) $(CXXFLAGS) $(SOURCE) -o $(OUTPUT)

VALIDATION_N       = 200
REFERENCE_OUTPUT   = ../../../reference/clbg/outputs/mandelbrot.pbm
BINARY_OUTPUT      = 1

include ../../../perfarena.mk
