LANG    = CSharp
TEST    = regex-redux
SOURCE  = Program.cs
OUTPUT  = bin/Release/regex-redux
ARG         = 0
RUN_CMD = dotnet run --configuration Release -- $(ARG)

COMPILE_CMD = dotnet build --configuration Release --nologo

VALIDATION_N       = 0
REFERENCE_OUTPUT   = ../../reference/outputs/regex-redux.txt
STDIN_FILE         = ../../reference/inputs/fasta-10000.txt

include ../../perfarena.mk
