LANG        = Python
TEST        = binary-trees
SOURCE      = binarytrees.python3
OUTPUT      = binarytrees.py
ARG         = 21
RUN_CMD     = python3 -OO $(OUTPUT) $(ARG)
COMPILE_CMD = cp $(SOURCE) $(OUTPUT)

